### ISSUE TITLE
Bug, overwriting

### ISSUE THREAD

**Issue by luckyde** [tufik2/TweenMaxRN#1]
Hey there,
I really hope you're still supporting this plugin because it's awesome! 
I'm having a bug every time I try to animate multiple properties of the same object

e.g. scale and translateX. 

It works if i go transform:{scale:2, ,translateX:20} but if I do it individually it bugs out telling me the second one's value is not a number. This happens with anything that follows the first, if i changed scale to translateY it does the same thing

video:

http://www.luckyde.com/bugB.mp4

Please let me know if theres anything i could do about this :)
Thanks

**Comment by tufik2** [comment]
Hi, this issue has been fixed and committed to master branch, also I note a small error in your code:
` 
tl.set(this.bounce, {style:{translateX:0, translateY:0, scale:1}}
for transform properties is necesarry alwaysuse transform instead style
tl.set(this.bounce, {transform:{translateX:0, translateY:0, scale:1}}
`

**Comment by luckyde** [comment]
Hi there, thanks for the update! I updated now to make sure its set to transform and I did another test, but with no luck sadly. Here I animated the scale separately at 3 seconds in(2 seconds after the translate finished) but it gave me the type isn't a number error
 http://www.luckyde.com/bugB_1.mp4

but if i remove the transform in the beggining it works fine. Am i doing something wrong in this code?
I tried to make sure in the begging that the initial scale and transform were set.
Thank you!

**Comment by tufik2** [comment]
mm, weird, can you verify that you updated src/libs/TweenMaxRN.js correctly? 
Sadly, this library is not an NPM repository yet so, you need to update the TweenMaxRN.js manually in your project. 

**Verify the version of the library**
In the header of the file, you will find the version, Something like this: (current version is is 0.0.2 
`
/* TweenMax RN v.0.0.2
    require('gsap');
    Example:
      TweenMax.fromTo(this.refs.view, 3, {style: {opacity: 0}, transform:{ translateY:200 } }, {style: {opacity: 1}, transform:{ translateY:0 }  } );
      <View ref="view" ... ></View>
*/
`

**Ensure that your package are well imported.**
import {TimelineMax} from "gsap";
require("src/libs/TweenMaxRN");

**If nothing work, please create a small GitHub project only with the reproduced issue and I will clone, check and verify what going on in that project and patch library if is necessary.**

**Comment by luckyde** [comment]
Apologies, I still had the old version, this worked! However if you try to do
.to( thing, 6, {transform:{translateY:600},0)
and then e.g. modify the scale while the transform is tweening e.g.
.to(thing, 1,{ transform: { scale: 1.1 }},1)
The scale will work but it will stop tweening the position until the scale is done tweening
See video:
http://www.luckyde.com/bugC.mp4

On the upside at least its not giving errors anymore, but its still overwriting itself sadly. But it feels a lot closer!

**Comment by luckyde** [comment]
If it helps I tried to ask the members of the GSAP forum about your plugins and I was told this
https://greensock.com/forums/topic/20484-gsap-on-react-native-question/?do=findComment&comment=95874
Maybe that has something to do with it?

**Comment by tufik2** [comment]
Hi luckyde, I was checking more in detail the code and wrote much stuff in the plugin... Thanks for your collaboration testing this plugin and let me know if you find more bugs...

**Some testing with the last version.**
````
let tl = new TimelineMax();
            tl.set(this.refs.box, {transform:{translateX:10, translateY:10, scale:1}, style:{backgroundColor:"#F00"} });
            tl.to(this.refs.box, 6, {transform:{translateY:300, scale:2}}, 0);
            tl.to(this.refs.box, 1, {transform:{translateX:200, rotate:"50deg"}}, 1);
            tl.to(this.refs.box, 1, {transform:{translateX:300}}, 2);
            tl.to(this.refs.box, 2, {transform:{scale:1}});
            tl.to(this.refs.box, 2, {transform:{rotate:"10deg"}, style:{backgroundColor:"#FFF"} });
            tl.fromTo(this.refs.box, 4, {transform:{translateX:0}}, {transform:{translateX:200}});
            tl.fromTo(this.refs.box, 4, {transform:{translateY:0}}, {transform:{translateY:200}}, "=-4");
            tl.to(this.refs.box, 2, {transform:{rotate:"0deg"}});

        let t2 = new TimelineMax();
            t2.set(this.refs.box2, {style:{left:0, top:0, backgroundColor:"#FF0", alpha:1}});
            t2.to(this.refs.box2, 4, {style:{top:400}}, 0);
            t2.to(this.refs.box2, 1, {style:{left:200, alpha:0.5}}, 1);
            t2.to(this.refs.box2, 1, {style:{left:100}}, 2);
            t2.to(this.refs.box2, 1, {style:{top:50, backgroundColor:"#0FF", alpha:1}});
            t2.fromTo(this.refs.box2, 4, {style:{left:0}}, {style:{left:100}, delay:1});
            t2.fromTo(this.refs.box2, 4, {style:{top:0}}, {style:{top:100}}, "=-4");

````
